"""Convert msgspec schemas into OpenAPI components and parameters."""

from __future__ import annotations

import inspect
from collections.abc import Callable
from copy import deepcopy
from types import UnionType
from typing import Any, Optional, Union, cast, get_origin

import msgspec

from defspec.models import OpenAPIParam, ParameterLocation, Schema

SchemaHook = Callable[[type], Schema]

__MSGSPEC_STRUCT_DOC__ = inspect.getdoc(msgspec.Struct)


def get_def_doc(obj: Any) -> str:
    """Get the docstring of a type."""
    doc = inspect.getdoc(obj)
    # Ignore msgspec's inherited Struct docstring.
    return doc if doc is not None and doc != __MSGSPEC_STRUCT_DOC__ else ""


def _constrain_parameter_schema(
    base: Schema,
    constraint: Schema,
) -> Schema:
    """Intersect schemas without overriding a constraint from either source."""
    if base is False or constraint is False:
        return False
    if base is True:
        return constraint
    if constraint is True or base == constraint:
        return base
    schema: dict[str, Any] = {"allOf": [base, constraint]}
    description = constraint.get("description", base.get("description"))
    if description is not None:
        schema["description"] = description
    return schema


def _check_parameter_constraints(
    schema: dict, properties: dict, *, allow_ref: bool = False, allow_meta: bool = True
):
    """Reject constraints that cannot be represented by separate parameters."""
    allowed = {"type", "properties", "required", "$comment"}
    if allow_meta:
        allowed |= {"title", "description"}
    if allow_ref:
        allowed.add("$ref")
    unsupported = schema.keys() - allowed
    if schema.get("type", "object") != "object":
        unsupported.add("type")
    if unsupported:
        raise ValueError(
            f"Cannot expand parameter model constraints: {', '.join(sorted(unsupported))}."
        )
    unknown = (
        schema.get("properties", {}).keys() | set(schema.get("required", []))
    ) - properties.keys()
    if unknown:
        raise ValueError(
            "Cannot expand parameter model constraints for undeclared fields: "
            f"{', '.join(sorted(unknown))}."
        )


def _parameter_model(schema: Schema, components: dict[str, Schema]) -> Schema:
    """Validate an object model and expand local reference constraints."""
    if not isinstance(schema, dict):
        return schema
    ref = schema.get("$ref", "")
    prefix = "#/components/schemas/"
    is_reference = ref.startswith(prefix)
    model = components.get(ref.removeprefix(prefix), {}) if is_reference else schema
    if (
        not isinstance(model, dict)
        or model.get("type") != "object"
        or "properties" not in model
    ):
        return schema

    _check_parameter_constraints(
        schema, model["properties"], allow_ref=is_reference, allow_meta=False
    )
    if not is_reference:
        return schema
    # Component titles and docstrings are generated by msgspec itself.
    _check_parameter_constraints(model, model["properties"])

    properties = model["properties"].copy()
    for name, constraint in schema.get("properties", {}).items():
        properties[name] = _constrain_parameter_schema(properties[name], constraint)
    return {
        **model,
        "properties": properties,
        "required": list(
            dict.fromkeys([*model.get("required", []), *schema.get("required", [])])
        ),
    }


def _schema_for_type(
    type_: Any,
    components: dict[str, Schema],
    schema_hook: Optional[SchemaHook],
) -> Schema:
    schemas, definitions = msgspec.json.schema_components(
        (type_,),
        # msgspec 0.20's stubs omit the True schemas supported at runtime.
        schema_hook=cast(Optional[Callable[[type], dict[str, Any]]], schema_hook),
        ref_template="#/components/schemas/{name}",
    )
    for name, definition in definitions.items():
        if not name:
            raise ValueError("Model names must not be empty.")
        if name in components and components[name] != definition:
            raise ValueError(
                f"Conflicting schema name {name!r}; use distinct model names."
            )
        components[name] = definition
    return schemas[0]


def _parameters(
    type_: Any,
    location: ParameterLocation,
    components: dict[str, Schema],
    schema_hook: Optional[SchemaHook],
) -> list[OpenAPIParam]:
    model = _parameter_model(
        _schema_for_type(type_, components, schema_hook), components
    )
    if (
        isinstance(model, dict)
        and model.get("type") == "object"
        and "properties" in model
    ):
        required = model.get("required", [])
        # Copy fields separately: hooks may reuse a schema dictionary.
        parameters = [
            OpenAPIParam(
                name=name,
                located_in=location,
                required=location == "path" or name in required,
                schema=deepcopy(field),
                description=(field.get("description") or msgspec.UNSET)
                if isinstance(field, dict)
                else msgspec.UNSET,
            )
            for name, field in model["properties"].items()
        ]
    elif location == "path":
        raise ValueError(
            "path_type must be a model whose fields match the URL placeholders."
        )
    else:
        name = getattr(type_, "__name__", None)
        # Python 3.14 gives unions the generic name "Union".
        if name is None or get_origin(type_) in (Union, UnionType):
            raise ValueError(
                f"{location}_type has no parameter name; use a model with named fields."
            )
        parameters = [
            OpenAPIParam(
                name=name,
                located_in=location,
                schema=deepcopy(model),
                description=get_def_doc(type_) or msgspec.UNSET,
            )
        ]
    if location == "header":
        reserved = [
            param.name
            for param in parameters
            if param.name.lower() in ("accept", "content-type", "authorization")
        ]
        if reserved:
            raise ValueError(
                f"Cannot define reserved header parameters: {', '.join(sorted(reserved))}. "
                "Use security schemes for Authorization and media types for "
                "Accept and Content-Type."
            )
    return parameters
