"""OpenAPI document models and shared schema types."""

from __future__ import annotations

import sys
from typing import Any, Literal, Optional, Union

import msgspec

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

DEFAULT_CONTENT_TYPE = "application/json"
ParameterLocation = Literal["query", "header", "cookie", "path"]
Schema = Union[dict[str, Any], bool]


class OpenAPIInfo(msgspec.Struct, kw_only=True):
    title: str = "OpenAPI"
    description: str = "OpenAPI generated by defspec"
    version: str = "0.1.0"


class OpenAPIParam(msgspec.Struct, kw_only=True):
    name: str
    located_in: ParameterLocation = msgspec.field(default="query", name="in")
    required: bool = True
    description: Union[str, msgspec.UnsetType] = msgspec.UNSET
    schema: Schema


class JSONSchema(msgspec.Struct, kw_only=True, omit_defaults=True):
    content: dict[str, dict] = msgspec.field(default_factory=dict)

    @classmethod
    def with_schema_content_type(
        cls, schema: Schema, content_type: Optional[str] = None
    ) -> Self:
        return cls(content={content_type or DEFAULT_CONTENT_TYPE: {"schema": schema}})


class OpenAPIRequestBody(JSONSchema):
    pass


class OpenAPIResponse(JSONSchema):
    description: str = ""

    def __post_init__(self):
        """Supply the response description required by OpenAPI."""
        if not self.description:
            self.description = "OK"


class OpenAPIRoute(msgspec.Struct, kw_only=True, omit_defaults=True):
    summary: str
    operation_id: str = msgspec.field(name="operationId")
    description: str = ""
    parameters: list[OpenAPIParam] = msgspec.field(default_factory=list)
    request_body: Union[OpenAPIRequestBody, msgspec.UnsetType] = msgspec.field(
        name="requestBody", default=msgspec.UNSET
    )
    responses: dict[str, OpenAPIResponse]
    security: Union[list[dict[str, list[str]]], msgspec.UnsetType] = msgspec.UNSET
    deprecated: bool = False


class SecuritySchemeHTTP(msgspec.Struct, tag_field="type", tag="http"):
    scheme: Literal["basic", "bearer"]


class SecuritySchemeAPIKey(msgspec.Struct, tag_field="type", tag="apiKey"):
    name: str
    located_in: Literal["query", "header", "cookie"] = msgspec.field(
        default="header", name="in"
    )


class SecuritySchemeOpenID(msgspec.Struct, tag_field="type", tag="openIdConnect"):
    open_id_connect_url: str = msgspec.field(name="openIdConnectUrl")


class _OAuthFlowMixin:
    __slots__ = ()
    refresh_url: Union[str, None, msgspec.UnsetType]

    def __post_init__(self):
        if self.refresh_url is None:
            self.refresh_url = msgspec.UNSET


class OAuthFlowAuthorizationCode(_OAuthFlowMixin, msgspec.Struct):
    authorization_url: str = msgspec.field(name="authorizationUrl")
    token_url: str = msgspec.field(name="tokenUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)


class ImplicitOAuthFlow(_OAuthFlowMixin, msgspec.Struct):
    authorization_url: str = msgspec.field(name="authorizationUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)


class PasswordOAuthFlow(_OAuthFlowMixin, msgspec.Struct):
    token_url: str = msgspec.field(name="tokenUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)


class ClientCredentialsOAuthFlow(PasswordOAuthFlow):
    pass


class OAuthFlow(msgspec.Struct, omit_defaults=True):
    """OAuth flow type.

    One or more named flows are supported.

    Previous name in OpenAPI 2.0:

    - `authorizationCode`: `accessCode`
    - `implicit`: `implicit`
    - `password`: `password`
    - `clientCredentials`: `application`
    """

    authorization_code: Optional[OAuthFlowAuthorizationCode] = msgspec.field(
        name="authorizationCode", default=None
    )
    implicit: Optional[ImplicitOAuthFlow] = None
    password: Optional[PasswordOAuthFlow] = None
    client_credentials: Optional[ClientCredentialsOAuthFlow] = msgspec.field(
        name="clientCredentials", default=None
    )

    def __post_init__(self):
        if not any(
            (
                self.authorization_code,
                self.implicit,
                self.password,
                self.client_credentials,
            )
        ):
            raise ValueError("At least one OAuth flow must be provided.")


class SecuritySchemeOAuth2(msgspec.Struct, tag_field="type", tag="oauth2"):
    flows: OAuthFlow


class OpenAPIComponent(msgspec.Struct, kw_only=True, omit_defaults=True):
    schemas: dict[str, Schema] = msgspec.field(default_factory=dict)
    security_schemes: dict[
        str,
        Union[
            SecuritySchemeHTTP,
            SecuritySchemeAPIKey,
            SecuritySchemeOAuth2,
            SecuritySchemeOpenID,
        ],
    ] = msgspec.field(name="securitySchemes", default_factory=dict)
