from __future__ import annotations

import inspect
import re
import sys
from collections import defaultdict
from collections.abc import Callable
from typing import Any, Literal, Optional, Union, get_args

import msgspec

from defspec.server import serve_openapi_http_daemon

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

DEFAULT_CONTENT_TYPE = "application/json"


class OpenAPIInfo(msgspec.Struct, kw_only=True):
    title: str = "OpenAPI"
    description: str = "OpenAPI generated by defspec"
    version: str = "0.1.0"


class OpenAPIParam(msgspec.Struct, kw_only=True):
    name: str
    located_in: Literal["query", "header", "cookie", "path"] = msgspec.field(
        default="query", name="in"
    )
    required: bool = True
    description: str = ""
    schema: Union[dict[str, Any], bool]


class JSONSchema(msgspec.Struct, kw_only=True, omit_defaults=True):
    content: dict[str, dict] = msgspec.field(default_factory=dict)

    @classmethod
    def with_schema_content_type(
        cls, schema: dict[str, Any], content_type: Optional[str] = None
    ) -> Self:
        instance = cls()
        content_type = content_type or DEFAULT_CONTENT_TYPE
        instance.content[content_type] = {"schema": schema}
        return instance


class OpenAPIRequestBody(JSONSchema):
    pass


class OpenAPIResponse(JSONSchema):
    description: str = ""

    def __post_init__(self):
        """To avoid omitting description field."""
        if not self.description:
            self.description = "OK"


class OpenAPIRoute(msgspec.Struct, kw_only=True, omit_defaults=True):
    summary: str
    operation_id: str = msgspec.field(name="operationId")
    description: str = ""
    parameters: list[OpenAPIParam] = msgspec.field(default_factory=list)
    request_body: Union[OpenAPIRequestBody, msgspec.UnsetType] = msgspec.field(
        name="requestBody", default=msgspec.UNSET
    )
    responses: dict[str, OpenAPIResponse]
    security: Union[list[dict[str, list[str]]], msgspec.UnsetType] = msgspec.UNSET
    deprecated: bool = False


class SecuritySchemeHTTP(msgspec.Struct, tag_field="type", tag="http"):
    scheme: Literal["basic", "bearer"]


class SecuritySchemeAPIKey(msgspec.Struct, tag_field="type", tag="apiKey"):
    name: str
    located_in: Literal["query", "header", "cookie"] = msgspec.field(
        default="header", name="in"
    )


class SecuritySchemeOpenID(msgspec.Struct, tag_field="type", tag="openIdConnect"):
    open_id_connect_url: str = msgspec.field(name="openIdConnectUrl")


class OAuthFlowAuthorizationCode(msgspec.Struct):
    authorization_url: str = msgspec.field(name="authorizationUrl")
    token_url: str = msgspec.field(name="tokenUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)

    def __post_init__(self):
        if self.refresh_url is None:
            self.refresh_url = msgspec.UNSET


class ImplicitOAuthFlow(msgspec.Struct):
    authorization_url: str = msgspec.field(name="authorizationUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)

    def __post_init__(self):
        if self.refresh_url is None:
            self.refresh_url = msgspec.UNSET


class PasswordOAuthFlow(msgspec.Struct):
    token_url: str = msgspec.field(name="tokenUrl")
    refresh_url: Union[str, None, msgspec.UnsetType] = msgspec.field(
        name="refreshUrl", default=msgspec.UNSET
    )
    scopes: dict[str, str] = msgspec.field(default_factory=dict)

    def __post_init__(self):
        if self.refresh_url is None:
            self.refresh_url = msgspec.UNSET


class ClientCredentialsOAuthFlow(PasswordOAuthFlow):
    pass


class OAuthFlow(msgspec.Struct, omit_defaults=True):
    """OAuth flow type.

    One or more named flows are supported.

    Previous name in OpenAPI 2.0:

    - `authorizationCode`: `accessCode`
    - `implicit`: `implicit`
    - `password`: `password`
    - `clientCredentials`: `application`
    """

    authorization_code: Optional[OAuthFlowAuthorizationCode] = msgspec.field(
        name="authorizationCode", default=None
    )
    implicit: Optional[ImplicitOAuthFlow] = None
    password: Optional[PasswordOAuthFlow] = None
    client_credentials: Optional[ClientCredentialsOAuthFlow] = msgspec.field(
        name="clientCredentials", default=None
    )

    def __post_init__(self):
        if not any(
            (
                self.authorization_code,
                self.implicit,
                self.password,
                self.client_credentials,
            )
        ):
            raise ValueError("At least one OAuth flow must be provided.")


class SecuritySchemeOAuth2(msgspec.Struct, tag_field="type", tag="oauth2"):
    flows: OAuthFlow


class OpenAPIComponent(msgspec.Struct, kw_only=True, omit_defaults=True):
    schemas: dict[str, dict] = msgspec.field(default_factory=dict)
    security_schemes: dict[
        str,
        Union[
            SecuritySchemeHTTP,
            SecuritySchemeAPIKey,
            SecuritySchemeOAuth2,
            SecuritySchemeOpenID,
        ],
    ] = msgspec.field(name="securitySchemes", default_factory=dict)


HTTP_METHODS = Literal[
    "get", "post", "put", "delete", "head", "options", "trace", "patch"
]

__MSGSPEC_STRUCT_DOC__ = inspect.getdoc(msgspec.Struct)


def get_def_doc(obj: Any) -> str:
    """Get the docstring of a type."""
    doc = inspect.getdoc(obj)
    if doc is None:
        return ""
    # `inspect.getdoc` will traverse the __mro__ of a type, so we need to check
    if doc == __MSGSPEC_STRUCT_DOC__:
        return ""
    return doc


def _constrain_parameter_schema(
    base: Union[dict[str, Any], bool],
    constraint: Union[dict[str, Any], bool],
) -> Union[dict[str, Any], bool]:
    """Intersect schemas without overriding a constraint from either source."""
    if base is False or constraint is False:
        return False
    if base is True:
        return constraint
    if constraint is True or base == constraint:
        return base
    schema: dict[str, Any] = {"allOf": [base, constraint]}
    description = constraint.get("description", base.get("description"))
    if description is not None:
        schema["description"] = description
    return schema


def _parameter_model(schema: dict, components: dict[str, dict]) -> dict:
    """Resolve a local model reference and preserve representable siblings."""
    ref = schema.get("$ref", "")
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        return schema
    model = components.get(ref.removeprefix(prefix), {})
    if model.get("type") != "object" or "properties" not in model:
        return schema

    supported = {
        "$ref",
        "type",
        "properties",
        "required",
        "title",
        "description",
        "$comment",
    }
    unsupported = schema.keys() - supported
    if "type" in schema and schema["type"] != "object":
        unsupported.add("type")
    if unsupported:
        raise ValueError(
            f"Cannot expand parameter model constraints: {', '.join(sorted(unsupported))}."
        )
    constraints = schema.get("properties", {})
    extra_required = schema.get("required", [])
    unknown = (constraints.keys() | set(extra_required)) - model["properties"].keys()
    if unknown:
        raise ValueError(
            "Cannot expand parameter model constraints for undeclared fields: "
            f"{', '.join(sorted(unknown))}."
        )
    # Work on copies: the referenced model may also describe a request body or
    # be reused by another operation without these parameter constraints.
    properties = model["properties"].copy()
    for name, constraint in constraints.items():
        properties[name] = _constrain_parameter_schema(properties[name], constraint)
    return {
        **model,
        "properties": properties,
        "required": list(dict.fromkeys([*model.get("required", []), *extra_required])),
    }


class OpenAPI(msgspec.Struct, kw_only=True):
    """OpenAPI specification.

    Usage:
        >>> openapi = OpenAPI()
        >>> # init with customized info
        >>> openapi = OpenAPI(
        >>>     info=OpenAPIInfo(title="My API", version="1.2.3"),
        >>>     components=OpenAPIComponent(
        >>>         security_schemes={
        >>>             "APIKey": SecuritySchemeAPIKey(name="X-Auth-Token")
        >>>         }
        >>>     ),
        >>> )
    """

    openapi: str = "3.1.0"
    info: OpenAPIInfo = msgspec.field(default_factory=OpenAPIInfo)
    paths: dict[str, dict[str, OpenAPIRoute]] = msgspec.field(
        default_factory=lambda: defaultdict(dict)
    )
    components: OpenAPIComponent = msgspec.field(default_factory=OpenAPIComponent)
    security: list[dict[str, list[str]]] = msgspec.field(default_factory=list)

    def __post_init__(self):
        if not re.fullmatch(r"3\.1\.\d+", self.openapi):
            raise ValueError("Only OpenAPI 3.1.x is supported.")

    @property
    def defs(self) -> dict[str, dict]:
        """Compatibility alias for components.schemas; never serialized as $defs."""
        return self.components.schemas

    def _schema_for_type(
        self,
        type_: Any,
        components: dict[str, dict],
        schema_hook: Optional[Callable[[type], dict[str, Any]]],
    ) -> dict:
        schemas, definitions = msgspec.json.schema_components(
            (type_,),
            schema_hook=schema_hook,
            ref_template="#/components/schemas/{name}",
        )
        for name, definition in definitions.items():
            if name in components and components[name] != definition:
                raise ValueError(
                    f"Conflicting schema name {name!r}; use distinct model names."
                )
            components[name] = definition
        return schemas[0]

    def _parameters(
        self,
        type_: Any,
        location: Literal["query", "header", "cookie", "path"],
        components: dict[str, dict],
        schema_hook: Optional[Callable[[type], dict[str, Any]]],
    ) -> list[OpenAPIParam]:
        schema = self._schema_for_type(type_, components, schema_hook)
        model = _parameter_model(schema, components)
        if model.get("type") == "object" and "properties" in model:
            required = model.get("required", [])
            return [
                OpenAPIParam(
                    name=name,
                    located_in=location,
                    required=location == "path" or name in required,
                    schema=field,
                    description=field.get("description", "")
                    if isinstance(field, dict)
                    else "",
                )
                for name, field in model["properties"].items()
            ]
        if location == "path":
            raise ValueError("path_type must be an object model with named fields.")
        return [
            OpenAPIParam(
                name=type_.__name__,
                located_in=location,
                schema=schema,
                description=get_def_doc(type_),
            )
        ]

    def _check_route(self, path: str, method: HTTP_METHODS, operation_id: str):
        if method not in get_args(HTTP_METHODS):
            raise ValueError(f"Unsupported OpenAPI 3.1 method: {method!r}")
        if not path.startswith("/") or "?" in path or "#" in path:
            raise ValueError(
                "Paths must start with '/' and omit queries and fragments."
            )
        normalized = re.sub(r"\{[^{}]+\}", "{}", path)
        literal_path = re.sub(r"\{[^{}]+\}", "", path)
        if "{" in literal_path or "}" in literal_path:
            raise ValueError(f"Malformed path template: {path!r}")
        for existing_path, routes in self.paths.items():
            if (
                existing_path != path
                and re.sub(r"\{[^{}]+\}", "{}", existing_path) == normalized
            ):
                raise ValueError(
                    f"Equivalent path template already exists: {existing_path!r}"
                )
            for existing_method, route in routes.items():
                if (existing_path, existing_method) != (
                    path,
                    method,
                ) and route.operation_id == operation_id:
                    raise ValueError(
                        f"Duplicate operationId {operation_id!r}; provide a unique operation_id."
                    )

    def register_route(  # noqa: PLR0913
        self,
        path: str,
        method: HTTP_METHODS,
        summary: Optional[str] = None,
        request_type: Any = None,
        request_content_type: Optional[str] = None,
        response_type: Any = None,
        response_content_type: Optional[str] = None,
        query_type: Any = None,
        header_type: Any = None,
        cookie_type: Any = None,
        deprecated: bool = False,
        schema_hook: Optional[Callable[[type], dict[str, Any]]] = None,
        *,
        path_type: Any = None,
        operation_id: Optional[str] = None,
        security: Optional[list[dict[str, list[str]]]] = None,
    ):
        """Register an OpenAPI 3.1 operation.

        Object parameter models expand into one parameter per encoded field name.
        Defaults determine optionality, except that path parameters are always required.
        Sibling properties and required constraints on a model reference can further
        constrain declared fields. Unsupported sibling constraints raise ValueError.
        Invalid routes and conflicting schema names raise ValueError without changing
        the document.

        Args:
            path: URL path; each {placeholder} must match a path_type field.
            method: Lowercase OpenAPI HTTP method (CONNECT is unsupported).
            summary: Summary of the operation.
            request_type: Request body type; None omits requestBody.
            request_content_type: Request media type, defaulting to application/json.
            response_type: Response body type; None describes a response without content.
            response_content_type: Response media type, defaulting to application/json.
            query_type: Query parameter model or named scalar type.
            header_type: Header parameter model or named scalar type.
            cookie_type: Cookie parameter model or named scalar type.
            deprecated: Whether the operation is deprecated.
            schema_hook: Callback for custom JSON Schema generation.
            path_type: Object model declaring all path parameters.
            operation_id: Unique operation ID; defaults to method plus path with
                slashes replaced by underscores. Collisions require an explicit ID.
            security: None inherits global security; [] makes the operation public.
        """
        operation_id = (
            operation_id
            if operation_id is not None
            else f"{method}_{path.replace('/', '_')}"
        )
        self._check_route(path, method, operation_id)
        # Stage all changes so a failure cannot overwrite an existing operation
        # or leave unused schema definitions behind.
        components = self.components.schemas.copy()
        request_body: Union[OpenAPIRequestBody, msgspec.UnsetType] = msgspec.UNSET
        if request_type is not None:
            request_body = OpenAPIRequestBody.with_schema_content_type(
                self._schema_for_type(request_type, components, schema_hook),
                request_content_type,
            )
        response = OpenAPIResponse()
        if response_type is not None:
            response = OpenAPIResponse.with_schema_content_type(
                self._schema_for_type(response_type, components, schema_hook),
                response_content_type,
            )
        parameters: list[OpenAPIParam] = []
        locations: tuple[Literal["query", "header", "cookie", "path"], ...] = (
            "query",
            "header",
            "cookie",
            "path",
        )
        for location, type_ in zip(
            locations, (query_type, header_type, cookie_type, path_type), strict=True
        ):
            if type_ is not None:
                parameters.extend(
                    self._parameters(type_, location, components, schema_hook)
                )
        placeholders = set(re.findall(r"\{([^{}]+)\}", path))
        path_parameters = {
            param.name for param in parameters if param.located_in == "path"
        }
        if placeholders != path_parameters:
            raise ValueError(
                "path_type fields must exactly match the path placeholders."
            )
        route = OpenAPIRoute(
            summary=summary or f"{method} from {path.replace('/', ' ')}",
            operation_id=operation_id,
            request_body=request_body,
            responses={"200": response},
            parameters=parameters,
            deprecated=deprecated,
            security=msgspec.UNSET if security is None else security,
        )
        self.components.schemas.update(components)
        self.paths.setdefault(path, {})[method] = route

    def to_json(self) -> bytes:
        """Convert to a JSON bytes that is commonly used in HTTP endpoint."""
        return msgspec.json.encode(self)

    def to_dict(self) -> dict:
        """Convert to a dict."""
        return msgspec.to_builtins(self)

    def serve_as_http_daemon(
        self, host: str = "127.0.0.1", port: int = 8080, run_in_background: bool = False
    ):
        """Serve the OpenAPI specification and UI as a HTTP server.

        - `/openapi/spec.json`: the OpenAPI specification
        - `/openapi/swagger`: the Swagger UI
        - `/openapi/redoc`: the ReDoc UI
        - `/openapi/scalar`: the Scalar UI

        Args:
            host: host to serve
            port: port to serve
            run_in_background: whether to run in a daemon thread
        """
        serve_openapi_http_daemon(host, port, run_in_background, self.to_json())
